### ISSUE TITLE
WebhookConfigurationTriggers does not contain configuration for subscription change event

### ISSUE THREAD

**Issue by sstuber** [ActiveCampaign/postmark-dotnet#110]
WebhookConfigurationTriggers is missing configuration for subscription change. This is available in the api according to https://postmarkapp.com/developer/api/webhooks-api#create-a-webhook. If you could add this in a new version, I would greatly appreciate it

**Comment by juliancarrivick** [comment]
I worked around this when creating a webhook by subclassing `WebhookConfigurationTriggers` and using it like so:

``` c#
public class PatchedWebhookConfigurationTriggers : WebhookConfigurationTriggers
{
    public WebhookConfigurationSubscriptionChangeTrigger? SubscriptionChange { get; set; }
}

public class WebhookConfigurationSubscriptionChangeTrigger
{
    public bool Enabled { get; set; }
}

...

await client.CreateWebhookConfigurationAsync(..., triggers: new PatchedWebhookConfigurationTriggers
{
    SubscriptionChange = new WebhookConfigurationSubscriptionChangeTrigger { Enabled = true },
});
```

This doesn't however help you if you want to retrieve the configuration using `client.GetWebhookConfigurationsAsync()`, but that was OK in my use case.
