### ISSUE TITLE
PostmarkResponse values missing / misleading when something fails

### ISSUE THREAD

**Issue by Skyppid** [ActiveCampaign/postmark-dotnet#115]
I just sent a batch message with `_client.SendMessagesAsync(...)` and was wondering why my join statement does return an empty array:
```
var result = recipients.Join((await _client.SendMessagesAsync(messages.ToArray())), recipient => recipient.Mail, response => response.To,
    (recipient, response) => (recipient, response)).ToArray();
```

Turns out that the send failed due to the template alias not existing (which is fine obviously). But then the response shouldn't be "Success" with missing "To" property and all. I expect the API to return an unsucessful result with appropriate `To` property so I know which message failed. Obviously in this case all will fail, but still. Why is the status `Success` then when there is an error code set? Why is the `To` property not set even if the client should know which recipient this response was for?

Looks like a little bit smell API there. Maybe this could be improved, as error handling becomes a lot harder this way :(

**Comment by MariuszTrybus** [comment]
Thank you for your report. The `Status` issue was resolved in #116 - version 4.7.7
