### ISSUE TITLE
Missing DeliveryType field in PostmarkServer

### ISSUE THREAD

**Issue by andrej-kocijan** [ActiveCampaign/postmark-dotnet#121]
When working with PostmarkDotnet, I've noticed that the Postmark server model is missing the "DeliveryType" field which is present in your API docs here: https://postmarkapp.com/developer/api/server-api .

Use case: I am working with some extremely sensitive clients, so no mails may be sent when testing under no circumstance. For that reason I want to ensure that when the environment is development, the code will throw an exception, if a live server is passed into the function.

For now I have solved that via a rather simple extension:
```c#
public class PostmarkServerWithDeliveryType : PostmarkServer
{
   public string DeliveryType { get; set; }
}

public class PostmarkClientExtension : PostmarkClient
{
    public PostmarkClientExtension(string apikey) : base(apikey)
    {
        
    }

    public async Task<PostmarkServerWithDeliveryType> GetServerWithDeliveryTypeAsync() => await this.ProcessNoBodyRequestAsync<PostmarkServerWithDeliveryType>("/server");
}
```
So now I can do the following:
```c#
if (_environment.IsDevelopment())
{
    PostmarkClientExtension clientLocal = new PostmarkClientExtension(postmarkApiKey);
    PostmarkServerWithDeliveryType serverWithDeliveryType = await clientLocal.GetServerWithDeliveryTypeAsync();
    
    if(serverWithDeliveryType.DeliveryType == "Live")
            throw new ForbiddenException($"You must provide a sandbox server when testing");
}

```

Is there a particular reason for this exclusion that I am not seeing?

I would be open to attempting to fix this myself and making a PR if that would be preferred :)
Thank you for your time

**Comment by MariuszTrybus** [comment]
Fixed in 4.7.8
