### ISSUE TITLE
[4.8.0] Serialization for TemplateModel of TemplatedPostmarkMessage doesn't seem to work with Dictionaries anymore

### ISSUE THREAD

**Issue by mvpindev** [ActiveCampaign/postmark-dotnet#130]
In the following screenshots "TemplateModel" is a Dictionary<string,object>

With previous Versions (Tested with 4.7.12)
![image](https://github.com/ActiveCampaign/postmark-dotnet/assets/49334712/882bd1ee-a748-4dcc-86c4-4bbfde54d65c)

Correctly converted by "JsonContent" in the "PostmarkClientBase.cs" class
![image](https://github.com/ActiveCampaign/postmark-dotnet/assets/49334712/79396275-d31e-491b-af34-60b9602073f4)

With 4.8.0 every value of the dictionary gets converted to an array:
![image](https://github.com/ActiveCampaign/postmark-dotnet/assets/49334712/c7ff4b48-79c6-44e9-a3e8-590c4ce67fab)

**Comment by MariuszTrybus** [comment]
Hey @mvpindev, I try to reproduce the issue but I can't get the TemplateModel values to get serialised as arrays, could you provide a small code snippet?

I tried
```csharp
var t1 = new Dictionary<string, object>
{
    { "tenant", new {  name = "Name1", logoUrl = "http://test1" } }
};

var t2 = new Dictionary<string, object>
{
    { "tenant", new Dictionary<string, object> { { "name", "Name1" }, { "logoUrl", "http://test1" } } }
};
```

and I get below in both cases
```
  "TemplateModel": {
    "tenant": {
      "name": "Name1",
      "logoUrl": "http://test1"
    }
  },
```

**Comment by mvpindev** [comment]
I'll try to create one asap

**Comment by mvpindev** [comment]
Hey @MariuszTrybus,

i was able to pinpoint what actually wrong.
My assumption of it being a dictionary of type Dictionary<string,object> was wrong.

Currently our code works similar to the following:
1. Microservice_1 creates a "TemplateModel" just like you did in your "t2"- Example
2. Microservice_1 sends a request including the Templatemodel to Microservice_2
3. Microservice_2 deserializes the Body with Newtonsoft.Json 

Which converts the templateModel from the RequestBody to the following:
```
var templateModel = new Dictionary<string, object>
{
     { "tenant", new Dictionary<string, Newtonsoft.Json.Linq.JToken> { { "name", "Name1" }, { "logoUrl", "http://test1" } } }
};
```

So i makes sense why it worked before in 4.7.12 where postmark-dotnet still used Newtonsoft internally.

I guess this can be closed, im sorry for the confusion

**Comment by MariuszTrybus** [comment]
Thank you for creating the ticket and sharing your findings. It's an edge case but it may help others in the future. I am sorry for any inconvenience caused by the change.
