### ISSUE TITLE
Change log?

### ISSUE THREAD

**Issue by gabephudson** [ActiveCampaign/postmark-dotnet#131]
Apologies if I have just missed it, but is there an active changelog for this API? The Github "releases" information stops at April 2021.

I see you have just moved from 4.8 to a 5.0 branch and am wondering if there are any breaking changes?

**Comment by MariuszTrybus** [comment]
Thank you for pointing this out. I've just added it for the newest release.

**Comment by TRCarbone** [comment]
Where is this? I can't find it or any release notes past version 2.

**Comment by rjgotten** [comment]
4.7.x releases are all missing there, for some reason.
