### ISSUE TITLE
Change `Status` when validation fails.

### ISSUE THREAD

**Issue by atheken** [ActiveCampaign/postmark-dotnet#42]
When validation fails in the postmark client, the PostmarkResponse class has a status of success. This is not really correct. It should be changed to "ValidationError" or similar, so that it can be identified more easily by the consumers of the client.

We should also add an option to the client to cause ValidationErrors to throw exceptions, as an alternative to checking the status codes, this would be backwards compatible with the current handling, which doesn't throw exceptions.

**Comment by tomasr78** [comment]
You should remove Exceptions completely if you provide Enum Status. Use Exceptions for errors or Status but not both. 

https://github.com/wildbit/postmark-dotnet/issues/77
